# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: beepcore
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: pesquisa-preco
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-pesquisa-preco

provider:
  name: aws
  runtime: nodejs22.x

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
